# Jekyll workshop-template evanwill
# https://github.com/evanwill/workshop-template
# based on minima theme https://github.com/jekyll/minima

# Notes: 
# - pages with "nav: true" in front matter will be in header nav
# - figure include for centered images, put file in images directory and use: {% include figure.html img="my-cat.jpg" alt="cat" caption="My cat" width="50%" %}

# Site settings
# title appears in the header
title: workshop-template
# description and keywords for meta tags
description: "Create an OER workshop website quick and easy!"
keywords: "workshops, OER, Open Education, websites, gh-pages, jekyll"

# author settings for cc-by, appears in the footer
author: evan will
pub_year: 2018
github_username: evanwill

# add the full url for the github repository
repo: "https://github.com/evanwill/workshop-template"

# site urls
# add the url for the domain,
# on gh-pages follow the pattern: https://username.github.io 
url: https://evanwill.github.io
# add subsection of the domain,
# on gh-pages this is a / followed by the name of the repository
baseurl: /workshop-template

# add google analytics if desired (optional)
# if blank, it will be ignored
# use JEKYLL_ENV=production on build command
google_analytics: 

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Build settings
markdown: kramdown
